routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainPageController;
use App\Http\Controllers\ArticleController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [MainPageController::class, 'index']);
Route::middleware(['auth'])->group(function () {
    Route::prefix('/article')->name('article.')->group(function () {
        Route::get('/', [ArticleController::class, 'index'])->name('index');
        Route::get('/form', [ArticleController::class, 'create'])->name('create');
        Route::post('/', [ArticleController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [ArticleController::class, 'edit'])->name('edit');
        Route::put('/', [ArticleController::class, 'update'])->name('update');
        Route::get('/edit/{id}/delete', [ArticleController::class, 'delete'])->name('delete');
    });
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});





require __DIR__ . '/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    const ROLE_USER = 'user';
    const ROLE_ADMIN = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models;
use Illuminate\Support\Facades\Auth;
use App\Models\Article;
use App\Models\Tag;
use Exception;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Log;
use App\Http\Requests\IncomingRequest;
use App\Http\Requests\EditIdRequest;
use App\Http\Requests\UpdateRequest;
use App\Http\Requests\DeleteRequest;



class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $id = Auth::id();

        $articles = Article::with(('tags'))
            ->where('user_id', $id)
            ->simplePaginate(10);




        return  view('article.index', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();

        return view('article.create', ['tags' => $tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(IncomingRequest $request, Article $article)
    {

        $user = Auth::user();
        try {
            DB::beginTransaction();
            $article->user_id = $user->id;
            $article->title = $request->title;
            $article->content = $request->content;
            $article->banner = $request->file('banner')->store('banners');
            $article->save();
            $article->tags()->sync($request->tags);
            DB::commit();
        } catch (Exception $ex) {
            //  Log::error($ex);
            DB::rollBack();
        }

        $validated = $request->validated();
        $validated = $request->safe()->only(['user_id', 'title', 'content', 'banner', 'tags',]);
        $validated = $request->safe()->except(['user_id', 'title', 'content', 'banner', 'tags',]);
        return $article;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(EditIdRequest $request, $id)
    {
        $tags = Tag::all();
        $article = Article::findOrFail($id);
        return view('article.edit', ['article' => $article], ['tags' => $tags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request)
    {
        $article = Article::findOrFail($request->id);
        $userId = Auth::id();
        if ($article->user_id !== $userId) {
            abort(403);
        }
        if ($request->hasFile('banner')) {
            $path = $request->file('banner')->store('banners');
            $previosBanner = $article->banner;
            $article->banner = $path;
        }

        $article->title = $request->title;
        $article->content = $request->content;
        $article->tags()->sync($request->tags);
        $article->save();

        if (isset($previosBanner)) {
            Storage::delete($previosBanner);
        }
        return redirect(route('article.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(DeleteRequest $request)
    {
        $article = Article::findOrFail($request->id);
        $userId = Auth::id();
        if ($article->user_id !== $userId) {
            abort(403);
        }
        $article->delete();
        return redirect(route('article.index'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainPageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MainPageController extends Controller
{
    public function index()
    {
        return view('main_page.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<article>


    <form method="POST" action="{{route('article.store')}}" enctype="multipart/form-data">
        @csrf
        <header class="entry-header">
            <h1 class="entry-title">Title</h1>
            @error('title')
            <div>{{ $message }}</div>
            @enderror
            <h1 class="entry-title">
                <input type="text" name="title" value="">
            </h1>
            <div class="entry-thumbnail">
                <h1 class="entry-title">Upload image</h1>
                <input type="file" name="banner">
            </div>
            @error('file')
            <div>{{ $message }}</div>
            @enderror
        </header>
        <!-- .entry-header -->
        <div class="entry-content">
            @error('content')
            <div>{{ $message }}</div>
            @enderror
            <textarea rows="6" name="content">Enter text</textarea>
        </div>
        <div class="entry-content" style="display: flex; flex-direction:column">
            @foreach($tags as $tag)
            @error('tags')
            <div>{{ $message }}</div>
            @enderror
            <input type="checkbox" id="{{$tag->name}}" name="tags[]" value="{{$tag->id}}">
            <label for="{{$tag->name}}">{{$tag->name}}</label>
            @endforeach
        </div>

        <!-- .entry-footer -->
        <button class="wpcmsdev-button color-green hentry" type="submit">Create</button>
    </form>
</article>
@endsection

resources/views/article/delete.blade.php
@extends('layouts.app')

@section('content')



@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<article>


    <form method="POST" action="{{route('article.update')}}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <input type="hidden" name="id" value="{{$article->id}}">
        <header class="entry-header">
            <h1 class="entry-title">Title</h1>
            @error('title')
            <div>{{ $message }}</div>
            @enderror
            <h1 class="entry-title">
                <input type="text" name="title" value="{{$article->title}}">
            </h1>
            <div class="entry-thumbnail">
                <a href="portfolio-item.html"><img src="/storage/{{$article->banner}}" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
            </div>
            <div class="entry-thumbnail">
                <h1 class="entry-title">Upload image</h1>
                <input type="file" name="banner">
            </div>
            @error('file')
            <div>{{ $message }}</div>
            @enderror
        </header>
        <!-- .entry-header -->
        <div class="entry-content">
            @error('content')
            <div>{{ $message }}</div>
            @enderror
            <textarea rows="6" name="content">{{$article->content}}</textarea>
        </div>
        <div class="entry-tags" style="display: flex; flex-direction:column">
            @foreach($tags as $tag)
            @error('tags')
            <div>{{ $message }}</div>
            @enderror
            <input type="checkbox" id="{{$tag->name}}" name="tags[]" value="{{$tag->id}}">
            <label for="{{$tag->name}}">{{$tag->name}}</label>
            @endforeach
        </div>
        <!-- .entry-footer -->
        <button class="wpcmsdev-button color-green hentry" type="submit">Create</button>



        <div class="entry-content">
            @error('content')
            <div>{{ $message }}</div>
            @enderror
            <h2 class="entry-title">
                <a href="{{route('article.delete', ["id" => $article->id])}}" rel="bookmark">Delete</a>
            </h2>

        </div>
    </form>

</article>
@endsection

resources/views/article/index.blade.php
@extends('layouts.app')

@section('content')
<div id="primary" class="content-area column full">
    <main id="main" class="site-main">
        <div class="grid portfoliogrid">
            @foreach($articles as $article)
            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="/storage/{{$article->banner}}" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title">
                        <a href="{{route('article.edit', ["id" => $article->id])}}" rel="bookmark">{{$article->title}}</a>
                    </h2>
                    @foreach($article->tags as $tag)
                    <a class='portfoliotype' href='portfolio-category.html'>{{$tag->name}}</a>
                    @endforeach
                </header>
            </article>
            @endforeach


        </div>
        <!-- .grid -->

        <nav class="pagination">
            <span class="page-numbers current">1</span>
            <a class="page-numbers" href="#">2</a>
            <a class="next page-numbers" href="#">Next »</a>
        </nav>
        <br />

    </main>
    <!-- #main -->
</div>
<!-- #primary -->
@endsection()

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Moschino | Minimalist Free HTML Portfolio by WowThemes.net</title>
    <link rel='stylesheet' href='css/woocommerce-layout.css' type='text/css' media='all' />
    <link rel='stylesheet' href='css/woocommerce-smallscreen.css' type='text/css' media='only screen and (max-width: 768px)' />
    <link rel='stylesheet' href='css/woocommerce.css' type='text/css' media='all' />
    <link rel='stylesheet' href='css/font-awesome.min.css' type='text/css' media='all' />
    <link rel='stylesheet' href='/css/style.css' type='text/css' media='all' />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Oswald:400,500,700%7CRoboto:400,500,700%7CHerr+Von+Muellerhoff:400,500,700%7CQuattrocento+Sans:400,500,700' type='text/css' media='all' />
    <link rel='stylesheet' href='css/easy-responsive-shortcodes.css' type='text/css' media='all' />
</head>

<body class="home page page-template page-template-template-portfolio page-template-template-portfolio-php">
    <div id="page">
        <div class="container">
            <header id="masthead" class="site-header">
                <div class="site-branding">
                    <h1 class="site-title"><a href="index.html" rel="home">Moschino</a></h1>
                    <h2 class="site-description">Minimalist Portfolio HTML Template</h2>
                </div>
                <nav id="site-navigation" class="main-navigation">
                    <button class="menu-toggle">Menu</button>
                    <a class="skip-link screen-reader-text" href="#content">Skip to content</a>
                    <div class="menu-menu-1-container">
                        <ul id="menu-menu-1" class="menu">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="about.html">About</a></li>
                            <li><a href="shop.html">Shop</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="elements.html">Elements</a></li>
                            <li><a href="contact.html">Contact</a></li>
                            @guest
                            <li><a href="{{route('register')}}">Registry</a></li>
                            <li><a href="{{route('login')}}">Login</a></li>
                            @endguest
                            @auth
                            <li><a href="{{route('article.create')}}">Create article</a></li>
                            <li>
                                <form method="POST" action="{{route('logout')}}">
                                    @csrf
                                    <button type="submit">
                                        Logout
                                    </button>
                                </form>
                            </li>

                            @endauth
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- #masthead -->
            <div id="content" class="site-content">
                @yield('content')
            </div>
            <!-- #content -->
        </div>
        <!-- .container -->
        <footer id="colophon" class="site-footer">
            <div class="container">
                <div class="site-info">
                    <h1 style="font-family: 'Herr Von Muellerhoff';color: #ccc;font-weight:300;text-align: center;margin-bottom:0;margin-top:0;line-height:1.4;font-size: 46px;">Moschino</h1>
                    <a target="blank" href="https://www.wowthemes.net/">&copy; Moschino - Free HTML Template by WowThemes.net</a>
                </div>
            </div>
        </footer>
        <a href="#top" class="smoothup" title="Back to top"><span class="genericon genericon-collapse"></span></a>
    </div>
    <!-- #page -->
    <script src='js/jquery.js'></script>
    <script src='js/plugins.js'></script>
    <script src='js/scripts.js'></script>
    <script src='js/masonry.pkgd.min.js'></script>
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/main_page/index.blade.php
@extends('layouts.app')


@section('content')
<div id="primary" class="content-area column full">
    <main id="main" class="site-main">
        <div class="grid portfoliogrid">

            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/30162427/p1.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Sunset Beach</a></h2>
                    <a class='portfoliotype' href='portfolio-category.html'>summer</a>
                    <a class='portfoliotype' href='portfolio-category.html'>woman</a>
                    <a class='portfoliotype' href='portfolio-category.html'>yellow</a>
                </header>
            </article>

            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/30160348/p5.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Earl of Moreland</a></h2>
                    <a class='portfoliotype' href='portfolio-category.html'>hat</a>
                    <a class='portfoliotype' href='portfolio-category.html'>woman</a>
                    <a class='portfoliotype' href='portfolio-category.html'>yellow</a>
                </header>
            </article>

            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/30160151/p3.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Eliza and John</a></h2>
                    <a class='portfoliotype' href='portfolio-category.html'>summer</a>
                    <a class='portfoliotype' href='portfolio-category.html'>woman</a>
                    <a class='portfoliotype' href='portfolio-category.html'>yellow</a>
                </header>
            </article>

            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/18160911/p6.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Hot Afternoon</a></h2>
                    <a class='portfoliotype' href='portfolio-category.html'>pink</a>
                    <a class='portfoliotype' href='portfolio-category.html'>woman</a>
                    <a class='portfoliotype' href='portfolio-category.html'>yellow</a>
                </header>
            </article>

            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/15223245/p2.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Long Walks</a></h2>
                    <a class='portfoliotype' href='portfolio-category.html'>hat</a>
                    <a class='portfoliotype' href='portfolio-category.html'>summer</a>
                    <a class='portfoliotype' href='portfolio-category.html'>yellow</a>
                </header>
            </article>

            <article class="hentry">
                <header class="entry-header">
                    <div class="entry-thumbnail">
                        <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/15222855/p7.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1" /></a>
                    </div>
                    <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Twilight</a></h2>
                    <a class='portfoliotype' href='portfolio-category.html'>hat</a>
                    <a class='portfoliotype' href='portfolio-category.html'>woman</a>
                    <a class='portfoliotype' href='portfolio-category.html'>summer</a>
                </header>
            </article>

        </div>
        <!-- .grid -->

        <nav class="pagination">
            <span class="page-numbers current">1</span>
            <a class="page-numbers" href="#">2</a>
            <a class="next page-numbers" href="#">Next »</a>
        </nav>
        <br />

    </main>
    <!-- #main -->
</div>
<!-- #primary -->
@endsection